---
title: "Fire weather data"
author: "Anna Talucci"
date: "September 6, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview


```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(statmod)
library(car)
library(DHARMa)
library(GGally)
library(MASS)
library(cowplot)
library(magick)

```

# Data

```{r}
weather = read.csv("../data/2019-09-06_AllFires_dailyweather_R.csv", header=TRUE, sep = ",", strip.white = TRUE)
head(weather)
```

```{r}
weather = weather %>% 
  mutate(Fire_name = ifelse(Fire_id %in% "R10171_2012", "Entiako",
                            ifelse(Fire_id %in% "R10070_2014", "Chelaslie","Tweedsmuir")))
```


```{r}
( fwi = ggplot(weather, aes(x=Fire_name, y=fwi, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2") +
    ylab(label="FWI") + 
  xlab("") +
  theme_bw(base_size = 12) +
                theme(plot.margin = unit(c(0.2, 0.2, 0.05, 0.5), "cm")) +
   theme(legend.position = "none") +

    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
```

```{r}
( rh = ggplot(weather, aes(x=Fire_name, y=rh, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2") +
    ylab(label="Relative Humidity") + 
  xlab("") +
  theme_bw(base_size = 12) +
                theme(plot.margin = unit(c(0.2, 0.2, 0.05, 0.5), "cm")) +
   theme(legend.position = "none") +

    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
```

```{r}
( temp = ggplot(weather, aes(x=Fire_name, y=temp, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2") +
    ylab(expression(paste("Temperature (",degree,"C)"))) + 
  xlab("") +
  theme_bw(base_size = 12) +
                theme(plot.margin = unit(c(0.2, 0.2, 0.05, 0.5), "cm")) +
   theme(legend.position = "none") +

    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
```

```{r}
( ws = ggplot(weather, aes(x=Fire_name, y=ws, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2") +
    ylab(label="Wind speed (m/s)") + 
  xlab("") +
  theme_bw(base_size = 12) +
                theme(plot.margin = unit(c(0.2, 0.2, 0.05, 0.5), "cm")) +
   theme(legend.position = "none") +
    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
```

    theme(plot.margin = unit(c(t = 0.3, r = 0.1, b = 0.3, l = 0.1), "cm")) +
```{r}
( burndate = ggplot(weather, aes(x=Fire_name, y=Burndate, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2") +
    ylab(label="Julian date") + 
  xlab("") +
  theme_bw(base_size = 12) +
                theme(plot.margin = unit(c(0.2, 0.2, 0.05, 0.5), "cm")) +
   theme(legend.position = "none") +

    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
``` 

```{r}
summary(weather$Fire_id)

```



```{r}
( legend_fwi = ggplot(weather, aes(x=Fire_name, y=Burndate, fill=Fire_id)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Dark2", name="Fire event", breaks=c("R10171_2012", "R10252_2013", "R10070_2014")) +
    ylab(label="Julian date") + 
  xlab("") +
  theme_bw() +
   theme(legend.position = "bottom") +
    theme(plot.margin = unit(c(t = 0.3, r = 0.1, b = 0.3, l = 0.1), "cm")) +
    theme(axis.title.x = element_text(size = 11, hjust = 0.5, vjust = -0.1),
        axis.title.y = element_text(size = 11, hjust = 0.5, vjust = 1.1),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 10, color = "black"),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) )
```

```{r fig.height=4.5, fig.width=6}
legend = cowplot::get_legend(legend_fwi)
(weather_plot1 = cowplot::plot_grid(fwi, rh, temp, ws, labels = c("(a)", "(b)", "(c)", "(d)"), label_fontface = 'plain', label_size = 12, align = "hv", ncol= 2)  )

(weather_plot2 = plot_grid(weather_plot1, legend, ncol=1, rel_widths = c(1, .1), rel_heights = c(1, .05)))
```

```{r eval=FALSE, include=FALSE}
ggsave("../figs/2019-09-27_fire_weather.tiff", plot = weather_plot1, width = 6, height = 4.5, units = c("in"), dpi=600 )
```
**THE END**